### ISSUE TITLE
Started apps doesn't really tell me about the instance state

### ISSUE THREAD

**Issue by skibum55** [krujos/usagereport-plugin#5]
As a platform operator 
I want to identify apps that are crashing
So that I can notify the developers to fix them

In the case of the following app, it is started, but all instances are _crashing_

```
requested state: started
instances: 0/2
usage: 1G x 2 instances
urls: vault.cfapps.pez.pivotal.io
last uploaded: Mon Sep 28 21:33:14 UTC 2015
stack: cflinuxfs2
buildpack: unknown

     state     since                    cpu    memory    disk      details
#0   crashed   2016-01-13 08:36:08 PM   0.0%   0 of 1G   0 of 1G
#1   crashed   2016-01-13 08:40:39 PM   0.0%   0 of 1G   0 of 1G
```

The response from the _instances_ endpoint `GET /v2/apps/5982c71a-62d0-416d-9028-6a2589c876c9/instances` gives me the following:

```
{"0":{"state":"CRASHED","uptime":176,"since":1452742568},"1":{"state":"CRASHED","uptime":8,"since":1452742736}}
```

Is this the place to add this functionality, or do we keep the focus on usage?

**Comment by krujos** [comment]
We could do it here, but would it make more sense to have a CF crashing plugin or dashboard app? Is the intent in the story that an operator catches it during a regular status check (so it's a bonus pro active "be nice" kinda thing) or are they looking for crashing apps? If it's the latter I think we would be better served by writing a dashboard instead of extending the plugin.

**Comment by krujos** [comment]
Or, what about adding it to the dr plugin? https://github.com/emirozer/cf-doctor-plugin

**Comment by krujos** [comment]
@skibum55 ?

**Comment by skibum55** [comment]
This doesn't really belong in this plugin.  Closing.
